scrape_configs:
  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # - job_name: 'users-service'
  #   static_configs:
  #     - targets: ['users-service:8000']
  
  # - job_name: 'orders-service'
  #   static_configs:
  #     - targets: ['orders-service:8002']
  
  # - job_name: 'products-service'
  #   static_configs:
  #     - targets: ['products-service:8003']
  
  # - job_name: 'gateway-service'
  #   static_configs:
  #     - targets: ['gateway-service:8004']